before_script:
  - cp/config/database.travis.yml config/database.yml
  - psql -c 'create database tomato_time_test;' -U postgres


language: ruby

rvm:
  - 2.6.3

cache: bundler

script:
  - bundle exec rake

services:
  - redis-server
  - postgresql
